#!/usr/bin/env php
<?php

use Voyager\Core\RenderedInstance;
use Symfony\Component\Console\Input\ArgvInput;

define('VENUSIAN_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var RenderedInstance $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleInquiry(new ArgvInput);

exit($status);
