#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('VENUSIAN_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleSketch(new ArgvInput);

exit($status);
